# Generated by Django 4.2.13 on 2024-05-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
