# Generated by Django 4.2.13 on 2024-05-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_alter_user_current_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='uz', max_length=5),
        ),
    ]
