# Generated by Django 4.2.13 on 2024-05-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='texts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
