# Generated by Django 5.0.6 on 2024-05-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_user_first_name_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_values',
            field=models.JSONField(default={}),
        ),
    ]
