# Generated by Django 5.0.6 on 2024-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_alter_user_current_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='texts',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='values',
            field=models.JSONField(default={}),
        ),
    ]
