# Generated by Django 4.2.13 on 2024-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_alter_userhistory_texts_alter_userhistory_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='', max_length=5),
        ),
    ]
