version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 8000:8003
        # env_file is used to manage the env variables of our project
        env_file:
            - ./.env
        depends_on:
            - redis
            - db

    db:
        image: postgres:16-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: postgresql
            POSTGRES_HOST: db
            POSTGRES_NAME: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT: 5432

    redis:
        restart: unless-stopped
        image: redis:7-alpine
        expose:
            - 6379

    celery_worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: /app/docker/backend/worker-entrypoint.sh
        volumes:
            - .:/app
        env_file:
            - ./.env
        depends_on:
            - redis
            - db

    celery_beat:
        build:
            context: .
            dockerfile: Dockerfile
        command: /app/docker/backend/beat-entrypoint.sh
        volumes:
            - .:/app
        env_file:
            - ./.env
        depends_on:
            - redis
            - db


volumes:
    postgres_data: {}