version: "3.8"

services:
    db:
        image: postgres:16
        container_name: dtb_postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        env_file:
            - ./.env
        ports:
            - "5432:5432"
    redis:
        image: redis:alpine
        container_name: dtb_redis
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dtb_django
        restart: always
        command: bash -c "python manage.py migrate && gunicorn djconfig.wsgi:application -w 4 -b 0.0.0.0:8005"
        volumes:
            - .:/code
        ports:
            - "8005:8005"
        expose:
            - "8005"
        env_file:
            - ./.env
        depends_on:
            - db
        environment:
            - DJANGO_SETTINGS_MODULE=djconfig.settings.prod
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dtb_bot
        restart: always
        command: python app.py
        env_file:
            - ./.env
        depends_on:
            - web
    celery:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dtb_celery
        restart: always
        command: celery -A djconfig worker --loglevel=INFO
        volumes:
            - .:/code
        env_file:
            - ./.env
        depends_on:
            - redis
            - web
    celery-beat:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dtb_beat
        restart: always
        command: celery -A djconfig.celery_app beat -l info
        volumes:
            - .:/code
        env_file:
            - ./.env
        depends_on:
            - redis
            - celery
            - web

volumes:
    postgres_data: