# Generated by Django 5.0.6 on 2024-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_datadict'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadict',
            name='users_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
