# Generated by Django 5.0.6 on 2024-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0003_datadict_users_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadict',
            name='texts_data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='datadict',
            name='json_data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='datadict',
            name='users_data',
            field=models.JSONField(default={}),
        ),
    ]
